name: price_calculator
type:
    - tool
    - workflow
activate: true

providers:
    - name: Google Cloud Platform
      currency: USD

      params:
        - standard_storage: 0.026

      controls:
        - label: Standard Storage
          name: standard_storage_value
          tooltip: Amount of standard file storage you need.
          units: GB
        #   min: 1
        #   max: 1024

      formula: >
        standard_storage * standard_storage_value

    # - name: Amazon S3
    #   currency:
    #   params:
    #   controls:
    #   formula:
