name: rssreader
type:
  - tool
  - workflow
activate: true

feeds:
    - https://rss.sciencedaily.com/top.xml
    - http://www.ncbi.nlm.nih.gov/news/feed/
    - http://rss.medicalnewstoday.com/aid-disasters.xml

news_per_feed: 10
